image:
  - Visual Studio 2019
  - macOS

skip_branch_with_pr: true
stack: python 3.12  # 改用 Python 3.12，这是目前可用的最新版本

environment:
  GITHUB_TOKEN:
    secure: hEp/g48KzstKyiDP+GIylG4JAsWF9v3/9yzam53hb/b+qOM23/e9jxsxiRwyJfjCQjFVLcRnAxUJIurM3nrYCDXS9sY8V32rX9MB/ZZcVx3ScRY6XSZosB0OfitTxVdI

for:
  -
    matrix:
      only:
        - image: Visual Studio 2019

    install:
      - python -m pip install --upgrade pip
      - pip install flet==0.25.1
      - pip install selenium==4.27.1
      - pip install beautifulsoup4==4.12.3
      - pip install pandas==2.1.4  # 使用较早的稳定版本
      - pip install webdriver-manager==4.0.2
      - pip install pyinstaller

    build_script:
      - flet pack src/main.py --name "amazon-review-scraper" --icon src/assets/icon_windows.png --product-name "亚马逊评论爬虫" --product-version "1.0.0"

    after_build:
      - 7z a amazon-review-scraper-windows.zip %CD%\dist\*.exe

    artifacts:
      - path: amazon-review-scraper-windows.zip

  -
    matrix:
      only:
        - image: macOS

    install:
      - python3 -m pip install --upgrade pip
      - pip3 install flet==0.25.1
      - pip3 install selenium==4.27.1
      - pip3 install beautifulsoup4==4.12.3
      - pip3 install pandas==2.1.4
      - pip3 install webdriver-manager==4.0.2
      - pip3 install pyinstaller

    build_script:
      - flet pack src/main.py --name "amazon-review-scraper" --icon src/assets/icon_macos.png --product-name "亚马逊评论爬虫" --product-version "1.0.0" --build-arch arm64

    after_build:
      - tar -czvf amazon-review-scraper-macos.tar.gz -C dist amazon-review-scraper.app

    artifacts:
      - path: amazon-review-scraper-macos.tar.gz

test: off

deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  artifact: amazon-review-scraper-windows.zip, amazon-review-scraper-macos.tar.gz
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true

notifications:
  - provider: Email
    to:
      - heyong@kaimeichen.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true